name: Build and Deploy to Cloud Run

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Docker Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/jwt-authentication-microservice:latest .

      - name: Docker Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/jwt-authentication-microservice:latest

      - name: Deploy
        run: |
          gcloud run deploy jwt-authentication-microservice \
          --port 80 \
          --region asia-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/jwt-authentication-microservice:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
